version: '3.1'

services:

  nessus:
    image: tenable/nessus:latest-ubuntu

    restart: unless-stopped
    container_name: nessus
    environment:
      USERNAME: admin
      PASSWORD: admin
    ports:
      - 8834:8834
