# You will need to create a user for zabbix in your mysql database
# Also you will need to run create.sql in that database

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}       # Replace with your MySQL server hostname or IP
      MYSQL_USER: ${MYSQL_USER}                # Your Zabbix database user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}        # Your Zabbix database password
      MYSQL_DATABASE: ${MYSQL_DATABASE}        # The name of the Zabbix database
    volumes:
      - zabbix_data:/var/lib/zabbix
    ports:
      - "10051:10051"
      - "161:161" # SNMP queries
      - "162:162" # SNMP traps
    network_mode: "host"
    restart: unless-stopped

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}       # Same as above
      MYSQL_USER: ${MYSQL_USER}                # Same as above
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}        # Same as above
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}      # Name of the Zabbix server service
      PHP_TZ: ${PHP_TZ}                         # Change to your timezone
    depends_on:
      - zabbix-server
    ports:
      - "5757:8080"
    volumes:
      - zabbix_web_data:/etc/zabbix/web
    restart: unless-stopped

  # It is recommended that you run this on the actual host, bare metal
  # zabbix-agent:
  #   image: zabbix/zabbix-agent:latest
  #   environment:
  #     ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}      # Same as above
  #     ZBX_SERVER_PORT: 10051                    # Port for the Zabbix server
  #     ZBX_HOSTNAME: 'hostmachine'               # Hostname of the machine. This is what you enter in the frontend
  #   depends_on:
  #     - zabbix-server
  #   ports:
  #     - "10050:10050"                          # Agent port
  #   restart: unless-stopped

volumes:
  zabbix_data:
  zabbix_web_data:
